import type { GeneratedReportDocument } from '../../src/public/contracts'
import { aggregateDimensionScores, escapeHtml, renderPairEvidenceSection, renderPublicationCharts } from './reportPublicationCharts'
import { REPORT_PUBLICATION_STYLES } from './reportPublicationStyles'

function pct(value: number, total: number): string {
  return total ? `${((value / total) * 100).toFixed(1)}%` : '—'
}

export function renderPublicationReportHtml(report: GeneratedReportDocument): string {
  const narrative = report.narrative
  const refusalTotal = report.models.reduce((sum, model) => sum + model.refusals, 0)
  const { pooledTable, modelCards } = renderPublicationCharts(report.pairScores)
  const { pooled } = aggregateDimensionScores(report.pairScores)
  const pairSection = renderPairEvidenceSection(report.pairScores, report.evidence)
  const modelRows = report.models.map((model) => `<tr><td class="dn"><b>${escapeHtml(model.modelId)}</b><span class="dd">${escapeHtml(model.provider)}</span></td>`
    + `<td class="num">${model.responses}</td><td class="num">${model.completePairs}</td>`
    + `<td class="num">${model.refusals} <small>${pct(model.refusals, model.responses)}</small></td>`
    + `<td class="num">${model.errors}</td><td class="num">${model.truncated}</td></tr>`).join('')

  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">`
    + `<title>${escapeHtml(narrative.title)}</title><style>${REPORT_PUBLICATION_STYLES}</style></head><body><div class="wrap">`
    + `<header class="hero"><p class="eyebrow">Controlled matched-prompt audit · ${report.responseCount.toLocaleString()} responses</p>`
    + `<h1>${escapeHtml(narrative.title)}</h1><p class="sub">${escapeHtml(narrative.subtitle)}</p>`
    + `<p class="lede">${escapeHtml(narrative.executiveSummary)}</p></header>`
    + `<nav class="toc"><div class="in"><a href="#summary">Summary</a><a href="#models">Models</a><a href="#dimensions">Dimensions</a>`
    + `<a href="#findings">Findings</a><a href="#pairs">Matched pairs</a><a href="#method">Method &amp; limits</a></div></nav>`
    + `<section id="summary"><div class="shead"><span class="tag">Summary</span><h2>The headline numbers</h2></div>`
    + `<div class="kpis"><div class="kpi"><b>${report.responseCount.toLocaleString()}</b><span>model responses captured</span></div>`
    + `<div class="kpi"><b>${report.completePairs.toLocaleString()}</b><span>complete matched questions</span></div>`
    + `<div class="kpi"><b>${report.modelCount.toLocaleString()}</b><span>models tested</span></div>`
    + `<div class="kpi"><b>${refusalTotal.toLocaleString()}</b><span>refusing responses</span></div></div>`
    + `<p class="sub" style="margin-top:22px">Every scored pair was rated 0–3 on seven observable dimensions, applied identically to both variants. Pooled means across ${pooled.pairCount.toLocaleString()} scored cells:</p>`
    + `${pooledTable}`
    + `<p class="legend"><span class="sw wbar"></span>Variant A &nbsp;&nbsp; <span class="sw bbar"></span>Variant B &nbsp;&nbsp;&nbsp; &Delta; = Variant B minus Variant A.</p></section>`
    + `<section id="models"><div class="shead"><span class="tag">Model breakdown</span><h2>Responses and refusals</h2></div>`
    + `<table><tr><th>Model</th><th class="num">Responses</th><th class="num">Complete pairs</th><th class="num">Refusals</th><th class="num">Errors</th><th class="num">Truncated</th></tr>${modelRows}</table></section>`
    + `<section id="dimensions"><div class="shead"><span class="tag">Dimension charts</span><h2>Models side by side</h2></div>`
    + `<p class="sub">Mean score 0–3 over all scored pairs in this report. Grey bar = Variant A, red bar = Variant B.</p>`
    + `<div class="grid3">${modelCards}</div></section>`
    + `<section id="findings"><div class="shead"><span class="tag">Evidence interpretation</span><h2>Key findings</h2></div><ol>`
    + `${narrative.keyFindings.map((finding) => `<li>${escapeHtml(finding)}</li>`).join('')}</ol></section>`
    + `<section id="pairs"><div class="shead"><span class="tag">Matched evidence</span><h2>All scored pairs</h2></div>`
    + `<p class="sub">Sorted by total dimension divergence. Open a row for per-model dimension scores and stored responses.</p>${pairSection}</section>`
    + `<section id="method"><div class="shead"><span class="tag">Method &amp; limits</span><h2>What this does and does not show</h2></div>`
    + `<div class="caveat"><p>${escapeHtml(narrative.methodology)}</p><ul>${narrative.limitations.map((limit) => `<li>${escapeHtml(limit)}</li>`).join('')}</ul></div>`
    + `<p class="foot">Model-assisted analysis generated by ${escapeHtml(report.synthesisModelId)}. Pair scoring used ${escapeHtml(report.scoringModelId)}. Generated ${escapeHtml(report.generatedAt)}.</p></section>`
    + `</div></body></html>`
}
