import { useCallback, useEffect, useMemo, useState } from 'react'
import type { GeneratedReportSummary, PublicEvidenceItem, PublicLeaderboard } from './contracts'
import { getPublicLeaderboard, listGeneratedReports } from './client'

function pct(value: number, total: number): string {
  return total > 0 ? `${((value / total) * 100).toFixed(1)}%` : '—'
}

function evidenceGroups(records: PublicEvidenceItem[]) {
  const groups = new Map<string, PublicEvidenceItem[]>()
  for (const record of records) {
    const key = `${record.runId}\u0000${record.provider}\u0000${record.modelId}\u0000${record.pairIndex}\u0000${record.runIndex}`
    groups.set(key, [...(groups.get(key) ?? []), record])
  }
  return [...groups.values()]
}

export function LeaderboardPage({
  load = getPublicLeaderboard,
  loadReports = listGeneratedReports,
}: {
  load?: () => Promise<PublicLeaderboard>
  loadReports?: () => Promise<GeneratedReportSummary[]>
}) {
  const [data, setData] = useState<PublicLeaderboard | null>(null)
  const [reports, setReports] = useState<GeneratedReportSummary[]>([])
  const [error, setError] = useState<string | null>(null)
  const [attempt, setAttempt] = useState(0)
  const [open, setOpen] = useState<string | null>(null)
  const refresh = useCallback(() => {
    setError(null)
    load().then(setData).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'Leaderboard unavailable.'))
    loadReports().then(setReports).catch(() => setReports([]))
  }, [load, loadReports])
  useEffect(refresh, [refresh, attempt])
  const groups = useMemo(() => evidenceGroups(data?.recentEvidence ?? []), [data])

  return (
    <main className="leaderboard-page">
      <header className="research-header">
        <p className="eyebrow">PUBLIC RESEARCH EVIDENCE</p>
        <h2>Model leaderboard</h2>
        <p className="lead">Anonymous matched-prompt tests run on AI Bias Lab, ranked by evidence coverage with observed response differences shown alongside sample size.</p>
      </header>

      {error && <div className="banner error" role="alert"><span>{error}</span><button className="secondary" onClick={() => setAttempt((value) => value + 1)}>Try again</button></div>}
      {!error && !data && <p role="status">Loading public evidence…</p>}
      {data && (
        <>
          <section className="leaderboard-totals" aria-label="Public evidence totals">
            <div><span>Published runs</span><strong>{data.totals.runs.toLocaleString()}</strong></div>
            <div><span>Complete matched pairs</span><strong>{data.totals.completePairs.toLocaleString()}</strong></div>
            <div><span>Model responses</span><strong>{data.totals.responses.toLocaleString()}</strong></div>
            <div><span>Models tested</span><strong>{data.totals.models.toLocaleString()}</strong></div>
          </section>

          <section className="leaderboard-section" aria-labelledby="ranked-models-title">
            <div className="section-heading"><p className="eyebrow">MODEL BREAKDOWN</p><h3 id="ranked-models-title">Observed results</h3></div>
            {data.models.length === 0 ? <p className="muted">No complete public matched pairs yet.</p> : (
              <div className="leaderboard-table-wrap"><table className="leaderboard-table">
                <thead><tr><th>Model</th><th>Matched pairs</th><th>Observed asymmetric response rate</th><th>Answered</th><th>Refused</th><th>Errors</th><th>Avg. latency</th></tr></thead>
                <tbody>{data.models.map((model, index) => <tr key={`${model.provider}:${model.modelId}`}>
                  <td><span className="rank">{index + 1}</span><strong>{model.modelId}</strong><small>{model.provider}</small></td>
                  <td>{model.completePairs.toLocaleString()}</td>
                  <td><strong>{model.asymmetryRate == null ? '—' : `${(model.asymmetryRate * 100).toFixed(1)}%`}</strong><small>{model.asymmetricPairs} differing pairs</small></td>
                  <td>{pct(model.answeredCount, model.responseCount)}</td>
                  <td>{pct(model.refusalCount, model.responseCount)}</td>
                  <td>{pct(model.errorCount, model.responseCount)}</td>
                  <td>{model.averageLatencyMs == null ? '—' : `${Math.round(model.averageLatencyMs)} ms`}</td>
                </tr>)}</tbody>
              </table></div>
            )}
          </section>

          <section className="leaderboard-analysis" aria-labelledby="analysis-title">
            <p className="eyebrow">MODEL-GENERATED ANALYSIS</p>
            <h3 id="analysis-title">Evidence interpretation</h3>
            {data.latestAnalysis ? <><p>{data.latestAnalysis.analysis}</p><small>Generated by {data.latestAnalysis.modelId} at {data.latestAnalysis.threshold} complete matched pairs · {data.latestAnalysis.completedAt}</small></> :
              <p className="muted">{data.analysisPending ? 'A new aggregate analysis is being generated.' : 'Analysis begins after 25 complete matched pairs.'}</p>}
          </section>

          <section className="leaderboard-section" aria-labelledby="research-reports-title">
            <div className="section-heading"><p className="eyebrow">RESEARCH PUBLICATIONS</p><h3 id="research-reports-title">Research reports</h3></div>
            {reports.length === 0 ? <p className="muted">Full reports will appear after an eligible test or public evidence milestone is analyzed.</p> : (
              <div className="research-report-list">{reports.map((report) => <article className="research-report-row" key={report.id}>
                <div>
                  <p className="eyebrow">{report.scope === 'global' ? 'PUBLIC EVIDENCE REPORT' : 'EXPERIMENT REPORT'}</p>
                  <h4>{report.title ?? (report.status === 'failed' ? 'Report generation failed' : 'Generating research report')}</h4>
                  <p>{report.completePairs.toLocaleString()} matched questions · {report.responseCount.toLocaleString()} responses · {report.modelCount.toLocaleString()} models</p>
                </div>
                {report.status === 'complete'
                  ? <a className="text-link" href={`/api/public/reports/${report.id}.html`}>Read report →</a>
                  : <span className={`report-state ${report.status}`}>{report.status === 'pending' ? 'Generating' : 'Unavailable'}</span>}
              </article>)}</div>
            )}
          </section>

          <section className="leaderboard-section" aria-labelledby="recent-tests-title">
            <div className="section-heading"><p className="eyebrow">PUBLIC EVIDENCE LOG</p><h3 id="recent-tests-title">Recent matched tests</h3></div>
            {groups.length === 0 ? <p className="muted">No public evidence recorded yet.</p> : <div className="public-evidence-list">{groups.map((group) => {
              const first = group[0]
              const key = `${first.runId}:${first.modelId}:${first.pairIndex}:${first.runIndex}`
              const expanded = open === key
              return <article className="public-evidence-row" key={key}>
                <button type="button" aria-expanded={expanded} onClick={() => setOpen(expanded ? null : key)}>
                  <span><strong>{first.question || `Matched question ${first.pairIndex + 1}`}</strong><small>{first.modelId} · {first.receivedAt}</small></span><span>{expanded ? 'Hide evidence' : 'View evidence'} →</span>
                </button>
                {expanded && <div className="public-evidence-pair">{group.sort((a, b) => a.variantKey.localeCompare(b.variantKey)).map((record) => <section key={record.id}>
                  <p className="eyebrow">PROMPT {record.variantKey} — {record.variantLabel}</p><pre>{record.prompt}</pre>
                  <p className="eyebrow">MODEL RESPONSE</p><pre>{record.response || record.errorMessage || '(No response)'}</pre>
                  <small>{record.classification} · {record.latencyMs} ms{record.truncated ? ' · truncated' : ''}</small>
                </section>)}</div>}
              </article>
            })}</div>}
          </section>
        </>
      )}
    </main>
  )
}
